apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant-auto-frontend
  labels:
    app: assistant-auto
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assistant-auto
      component: frontend
  template:
    metadata:
      labels:
        app: assistant-auto
        component: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: assistant-auto-frontend
        image: ${DOCKER_USERNAME}/assistant-auto-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: REACT_APP_API_URL
          value: "https://api.assistant-auto-ultime.com"
        - name: REACT_APP_ENVIRONMENT
          value: "production"
        - name: REACT_APP_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: assistant-auto-frontend-secrets
              key: REACT_APP_SENTRY_DSN
        - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: assistant-auto-frontend-secrets
              key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        - name: REACT_APP_GOOGLE_ANALYTICS_ID
          valueFrom:
            secretKeyRef:
              name: assistant-auto-frontend-secrets
              key: REACT_APP_GOOGLE_ANALYTICS_ID
---
apiVersion: v1
kind: Service
metadata:
  name: assistant-auto-frontend
  labels:
    app: assistant-auto
    component: frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: assistant-auto
    component: frontend
---
apiVersion: v1
kind: Secret
metadata:
  name: assistant-auto-frontend-secrets
type: Opaque
data:
  # Exemple - ces valeurs doivent être remplacées par des valeurs encodées en base64
  REACT_APP_STRIPE_PUBLISHABLE_KEY: cGtfdGVzdF8qKioqKioqKioqKioqKioqKioqKioqKioqKioqKg==
  REACT_APP_SENTRY_DSN: aHR0cHM6Ly95b3VyLXByb2plY3Qta2V5QHNlbnRyeS5pby95b3VyLXByb2plY3QtaWQ=
  REACT_APP_GOOGLE_ANALYTICS_ID: Ry1YWFhYWFhYWFhY
